#!/bin/sh

# this script can be found at https://github.com/losingkeys/dmenu-custom

if [ "$1" = "-w" -o "$1" = "--new-window" ]; then
  newWindow=true
fi

websitesList="$HOME/.dmenu-web"
terminalProgramsList="$HOME/.dmenu-terminal"

if [ -e "$websitesList" ]; then
   # use dmenu to ask the user to choose a website/program
   choice="$(
    printf "%s\n%s" \
    "$(grep -v ^# "$websitesList"   | \
       cut -d, -f2,3,4,5,6,7,8,9,10 | \
       tr , "\n"                    | \
       tr -d "[:blank:]"            | \
       sort -r                      | \
       uniq                         | \
       tr -s "\n"                   | \
       sort)" \
    "$(# shellcheck disable=SC2012
       ls /bin | \
       sort)" | \
    dmenu -i
  )"
else
  # FIXME not sure how to do this with find
  # (https://github.com/koalaman/shellcheck/wiki/Directive)
  # shellcheck disable=SC2012
  choice="$(ls /bin | dmenu -i)"
fi

# blank input
if [ -z "$(echo "$choice" | tr -d "[:blank:]")" ]; then
  exit 0
fi

url="$(
  grep -v "^#" "$websitesList"           | \
  grep --word-regexp "\(,\s*\)\+$choice" | \
  cut -d, -f1                            | \
  tr -d "[:blank:]"
)"

if [ "$url" ]; then
  if [ "$BROWSER" ]; then
    if [ "$BROWSER" = firefox ]; then
      firefox=true
    elif [ "$BROWSER" = chromium ]; then
      chromium=true
    fi
  elif [ -x "$(command -v firefox)" ]; then
    firefox=true
  elif [ -x "$(command -v chromium)" ]; then
    chromium=true
  fi

  if [ $firefox ]; then
    if [ $newWindow ]; then
      exec firefox -new-window "$url"
    else
      exec firefox "$url"
    fi
  elif [ $chromium ]; then
    if [ $newWindow ]; then
      exec chromium --app="$url"
    else
      exec chromium "$url"
    fi
  else
    exec "$BROWSER" "$url"
  fi

  echo Error opening a browser. 2>&1
  # shellcheck disable=2016
  echo 'Please set "$BROWSER", or install firefox or chromium.' 2>&1
  exit 1
fi

if [ -e "$terminalProgramsList" ]; then
  # chop the choice up so you can pass arguments via dmenu
  # (e.g. mutt -R to open a mutt (mail program) in read-only mode)
  firstWordOfChoice="$(echo "$choice" | cut -d" " -f1)"

  terminalProgram="$(
    grep -v "^#" "$terminalProgramsList" | \
    tr -sc "[:alpha:]" "\n"              | \
    grep "$firstWordOfChoice"            | \
    tr -d "[:blank:]"
  )"

  if [ -n "$terminalProgram" ]; then
    # allow word-splitting so arguments can be passed to programs
    # shellcheck disable=SC2086
    exec urxvt -e $choice
  fi
fi

# allow word-splitting so arguments can be passed to programs
# shellcheck disable=SC2086
exec $choice
